<?php
session_start();
include "includes/db_connect.php";

if (
    !isset($_SESSION["loggedin"]) ||
    $_SESSION["loggedin"] !== true ||
    !isset($_SESSION["role"]) ||
    $_SESSION["role"] !== "admin"
) {
    header("Location: login.php");
    exit();
}

date_default_timezone_set("Asia/Jerusalem");

$backup_file = "trailfinder_backup_" . date("Y_m_d_H_i_s") . ".sql";

header("Content-Type: application/sql; charset=utf-8");
header("Content-Disposition: attachment; filename=" . $backup_file);
header("Pragma: no-cache");
header("Expires: 0");

echo "-- TrailFinder Database Backup\n";
echo "-- Created at: " . date("Y-m-d H:i:s") . "\n";
echo "-- Generated by admin backup system\n\n";

echo "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
echo "SET FOREIGN_KEY_CHECKS = 0;\n";
echo "START TRANSACTION;\n\n";

$tables_result = $conn->query("SHOW TABLES");

if ($tables_result) {
    while ($table_row = $tables_result->fetch_array()) {

        $table_name = $table_row[0];
        $safe_table_name = str_replace("`", "``", $table_name);

        echo "\n-- --------------------------------------------------------\n";
        echo "-- Table structure for table `$safe_table_name`\n";
        echo "-- --------------------------------------------------------\n\n";

        echo "DROP TABLE IF EXISTS `$safe_table_name`;\n";

        $create_result = $conn->query("SHOW CREATE TABLE `$safe_table_name`");

        if ($create_result) {
            $create_row = $create_result->fetch_assoc();
            echo $create_row["Create Table"] . ";\n\n";
        }

        echo "-- Data for table `$safe_table_name`\n\n";

        $data_result = $conn->query("SELECT * FROM `$safe_table_name`");

        if ($data_result && $data_result->num_rows > 0) {

            $fields = $data_result->fetch_fields();
            $columns = [];

            foreach ($fields as $field) {
                $columns[] = "`" . str_replace("`", "``", $field->name) . "`";
            }

            while ($data_row = $data_result->fetch_assoc()) {

                $values = [];

                foreach ($data_row as $value) {
                    if ($value === null) {
                        $values[] = "NULL";
                    } else {
                        $values[] = "'" . $conn->real_escape_string($value) . "'";
                    }
                }

                echo "INSERT INTO `$safe_table_name` (" . implode(", ", $columns) . ") VALUES (" . implode(", ", $values) . ");\n";
            }

            echo "\n";
        }
    }
}

echo "\nCOMMIT;\n";
echo "SET FOREIGN_KEY_CHECKS = 1;\n";

exit();
?>